# =======================
# docker-compose.yml
# =======================
services:
  app:
    build: .
    container_name: fullstack_slemp
    volumes:
      - ./htdocs:/opt/slemp/data/www
      - ./panel:/opt/slemp
    ports:
      - "80:80"    # Akses PHP site
      - "3306:3306"  # Akses MariaDB
      - "7777:7777"  # Akses Panel Python langsung (tanpa proxy)
    tty: true
